"""initial schema

Revision ID: 26bd4dda309c
Revises: 
Create Date: 2026-07-26 19:17:03.457975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26bd4dda309c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Idempotent - already installed database-wide on the shared
    # yourserver.com instance, but needed for a fresh dev/test database
    # (e.g. the schema-per-test-run harness in Phase 2's test suite).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('hash', sa.Text(), nullable=False),
    sa.Column('doc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('embedding_model',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('embed', 'rerank', 'generate')", name='ck_embedding_model_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_model_slug'), 'embedding_model', ['slug'], unique=True)
    op.create_table('llmcache',
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('collection',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ignore_patterns', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('include_by_default', sa.Boolean(), nullable=False),
    sa.Column('update_command', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name')
    )
    op.create_index(op.f('ix_collection_owner_user_id'), 'collection', ['owner_user_id'], unique=False)
    op.create_table('collectiongrant',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('permission', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('granted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("permission IN ('read', 'write', 'admin')", name='ck_grant_permission'),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'user_id')
    )
    op.create_index(op.f('ix_collectiongrant_collection_id'), 'collectiongrant', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collectiongrant_user_id'), 'collectiongrant', ['user_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['hash'], ['content.hash'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'path')
    )
    op.create_index(op.f('ix_document_collection_id'), 'document', ['collection_id'], unique=False)
    op.create_index('ix_document_search_vector', 'document', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_search_vector', table_name='document', postgresql_using='gin')
    op.drop_index(op.f('ix_document_collection_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_collectiongrant_user_id'), table_name='collectiongrant')
    op.drop_index(op.f('ix_collectiongrant_collection_id'), table_name='collectiongrant')
    op.drop_table('collectiongrant')
    op.drop_index(op.f('ix_collection_owner_user_id'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('llmcache')
    op.drop_index(op.f('ix_embedding_model_slug'), table_name='embedding_model')
    op.drop_table('embedding_model')
    op.drop_table('content')
    # ### end Alembic commands ###
