"""add per-path collection contexts and user global context

Revision ID: 2c4074f0444c
Revises: 26bd4dda309c
Create Date: 2026-07-26 20:18:01.461624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c4074f0444c'
down_revision: Union[str, Sequence[str], None] = '26bd4dda309c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collectioncontext',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.Column('path_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'path_prefix')
    )
    op.create_index(op.f('ix_collectioncontext_collection_id'), 'collectioncontext', ['collection_id'], unique=False)
    op.drop_column('collection', 'context')
    op.add_column('user', sa.Column('global_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'global_context')
    op.add_column('collection', sa.Column('context', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_collectioncontext_collection_id'), table_name='collectioncontext')
    op.drop_table('collectioncontext')
    # ### end Alembic commands ###
